feat: support running cypress tests
SwissDataScienceCenter/renku-actions pull request #45
Opened 2022-11-30 10:10 UTC by ciyer

Support handling `#cypress` in the deploy command.

2022-12-05 10:30 UTC, andre-code reviewed
This is going to be very helpful, thank you. I find it useful to clarify in the description the difference between selenium tests and cypress tests.

2022-12-05 10:30 UTC, andre-code commented on test-renku-cypress/README.md
> +The `test-rnku-cypress` action **does not** tear down the deployment, but the `test-renku` action to run the Selenium-based tests does, and some care needs to be taken when running the Cypress tests
typo in `test-rnku-cypress`

2022-12-05 10:30 UTC, andre-code commented on check-pr-description/action.yaml
>      description: whether the tests should run or not
Could we clarity in this description that it only refers to Selenium tests?

2022-12-05 12:55 UTC, lorenzo-cavazzi requested changes
This looks great!
On top of the 2 comments from @andre-code , I was wondering if we need to keep the long commented sections on "We currently do not tear-down the renku deployment [...]" since you mentioned that on the Readme. I guess we can live with that for the moment being.
Would the alternative be moving the teardown somewhere else, so we execute them if any of the 2 tests run? Would you mind making a follow-up issue for that? (I fear I might miss something since I don't know much the actions)

2022-12-06 08:28 UTC, ciyer commented
Thanks for the comments everyone. I have addressed the typo + clarification request. 

> Would the alternative be moving the teardown somewhere else, so we execute them if any of the 2 tests run? Would you mind making a follow-up issue for that? (I fear I might miss something since I don't know much the actions)

It depends on where we are headed. If the plan is to eventually switch to cypress and fade out the selenium tests, then the alternative would be to put the teardown in the cypress action (which is why I left those sections there, but commented out). If the plan is to continue to support both tests in parallel, then we would need to move the teardown to a separate step, as you suggest.

I can create the issue, but we should decide what the target is.

2022-12-06 10:48 UTC, olevski commented
Just for completeness this is a PR where this new action is being used. https://github.com/SwissDataScienceCenter/renku-ui/pull/2182

2022-12-06 10:48 UTC, olevski approved these changes

2022-12-06 10:55 UTC, lorenzo-cavazzi approved these changes
Lgtm! :rocket: 

> I can create the issue, but we should decide what the target is.

As discussed offline, let's add both options to the issue -- we can pick a solution in a couple of months after seeing how it goes with the Cypress tests.

2022-12-06 13:17 UTC, merged